### ISSUE TITLE
[Core] Locality-aware leasing

### ISSUE THREAD

**Issue by clarkzinzow** [ray-project/ray#12812]
Add locality-aware scheduling to Ray in the form of locality-aware leasing.

### Background

When executing tasks on remote workers, transferring task dependencies to those workers adds task execution latency, creates unnecessary object store memory pressure, and takes up valuable cluster network bandwidth. For data-intensive workloads, task dependency transfer often becomes the most significant performance bottleneck. By taking the data locality of task dependencies into account during scheduling decisions, we can minimize these undesirable effects of task dependency transfer. Namely, we can associate a cost with each task dependency that would have to be transferred to a worker, and we can choose to schedule the task onto a worker with minimum such cumulative cost (while accommodating other scheduling constraints/heuristics).

### Design

**Locality-aware leasing.** For a given task’s dependencies, fetch all requisite locality information (object locations and object size) at the time of future resolution (object is materialized in the cluster) from the object owner. When choosing a raylet to request a worker lease, construct a task dependency transfer (locality) cost for each node that holds a task dependency and choose to request a lease from the node with the least such cost (falling back to the local raylet). On spillback, the raylet returns the full set of candidates that adhere to soft/hard resource constraints to the submitting core worker, at which point that core worker chooses to request a lease from the node with the least locality cost out of that returned set of candidates.

See [design doc](https://docs.google.com/document/d/1-V1hMYijBAXtciDOdHVjZZlb-GRjNZNK20EiSqfYLyg/edit#) for more details.

### Milestones

- [x] [Milestone 1](https://github.com/ray-project/ray/issues/12813) - Locality cost only includes owned refs, and only considers pinned object locations.
- [x] [Milestone 2](https://github.com/ray-project/ray/issues/12814) - Locality cost includes non-pinned (cached) object locations for owned refs
- [ ] [Milestone 3](https://github.com/ray-project/ray/issues/12815) - Locality-aware spillback
- [x] [Milestone 4](https://github.com/ray-project/ray/issues/12816) - Locality cost includes borrowed refs

See the [design doc](https://docs.google.com/document/d/1-V1hMYijBAXtciDOdHVjZZlb-GRjNZNK20EiSqfYLyg/edit#heading=h.fp0b3hck1kxw) for further milestone details and the development plan.

**Comment by clarkzinzow** [comment]
@rkooo567 @stephanie-wang @ericl This parent issue would probably be better expressed as a GitHub milestone containing 4+ issues as subtasks, but I don't have permissions to create a milestone or assign tasks to a milestone so I went with a plain GitHub issue. If y'all would rather represent this as a milestone, please feel free to do the conversion!

**Comment by zhe-thoughts** [comment]
@clarkzinzow Quick verification: this is only for tasks (instead of also for actors) right?

**Comment by clarkzinzow** [comment]
@zhe-thoughts Yes, this is only for non-actor tasks! Actor tasks are executed on the same worker that hosts the particular actor, and actors are created without knowledge of future actor task dependencies, so there didn't seem to be much of an opportunity for locality-aware scheduling in actor task execution or actor creation.

**Comment by rkooo567** [comment]
Spillback wasn't implemented yet, but we can always revisit when we discover issues. Closing it for now
