### ISSUE TITLE
Windows CI Failure Tracking

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#13208]
Several tests consistently broke on Windows.

- [ ] https://github.com/ray-project/ray/issues/13198
- [ ] https://github.com/ray-project/ray/issues/13199
- [ ] https://github.com/ray-project/ray/issues/13200
- [ ] https://github.com/ray-project/ray/issues/13201
- [ ] https://github.com/ray-project/ray/issues/13202
- [ ] https://github.com/ray-project/ray/issues/13205
- [ ] https://github.com/ray-project/ray/issues/13206

**Comment by zhe-thoughts** [comment]
Thanks for working on this @simon-mo . Do you think this is a complete list of seriously flaky Windows tests?

**Comment by richardliaw** [comment]
@zhe-thoughts not sure but we will update it as we go.

**Comment by amogkam** [comment]
FYI the tests that are failing due to a `Windows access violation` seem to be because of some pytest issue with our C++ DLLs, not because the test themselves are failing. I'm still including them here to keep track of them though.
