### ISSUE TITLE
[RFC] ray memory improvement

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#14428]
### Describe your feature request

We improved the output & usability of the `ray memory` command from this PR. https://github.com/ray-project/ray/pull/13444

Now that it is merged, we'd like to make proposals to improve the `ray memory` command further. Here's the brief roadmap. 

- [x] Use the same code for both `ray memory` and ray dashboard (https://github.com/ray-project/ray/pull/13444)
- [x] Support better summary & sort & grouping of ray memory (https://github.com/ray-project/ray/pull/13444)
- [x] Remove the old `ray memory` code and make `ray memory --stats-only` efficient. (https://github.com/ray-project/ray/pull/14423)
- [x] Summary should display the size of objects. Currently, we only display the number of reference types, but we also would like to show the size of them. (@micahtyong) #14520
- [x] Formatting. (@micahtyong) #14520
- [x] Formatting the units of object size `ray memory --units=MB` #14520
- [x] Being able to specify the number of sorted entries `ray memory -n 10` -> 10 entries per group. #14520
- [ ] dump output and run the command against the file. `ray memory --dump=memory.json; ray memory memory.json`.

Below can be implemented with the new ray htop feature.
- [ ] Pagination
- [ ] Filtering. We'd like to filter groups that are not important for users. 
- [ ] Interactive command. P2.

**Comment by rkooo567** [comment]
@ericl The last one is about dumping ray memory output. I will close this issue now as most of them are handled.
