### ISSUE TITLE
[Core Worker pubsub] Roadmap

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#14762]
### Describe your feature request

- [x] Wait for object eviction pubsub. [P0]
- [x] Implement batch long polling reply [P0]
- [x] Replace the WaitForRefRemoved RPC [P0] https://github.com/ray-project/ray/issues/14762
- [x] Extend it to the object directory code path. [P1]
- [ ] Refactor to use the swappable interface to use grpc streaming. [P2] -> probably next Q
- [ ] Integrate to grpc streaming. [P2] -> probably next Q

Once all of them is done, we can even implement a completely generalized pubsub util (that can be used for pubsub between two arbitrary core components.)

cc @clarkzinzow

**Comment by jovany-wang** [comment]
@rkooo567 Hi SangBin, can you @ me in those PRs? I'm interested in it and will follow up it.

**Comment by rkooo567** [comment]
@jovany-wang https://github.com/ray-project/ray/pull/14638 here you go.

**Comment by rkooo567** [comment]
This is mostly done. Streaming is TBD until we integrate it + understand the semantics (if streaming limits the # of concurrent connections, it might not be a good use case for this).
