### ISSUE TITLE
[Release] 1.3 Checklist (Target date 4/22)

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#15021]
# Initial Steps
- [x]  Called for release blockers
  - [x]  Messaged Ant about release blockers
- [x]  Announced branch cut date and estimated release date

# Branch Cut
- [x]  Release branch created
- [ ]  Release branch versions updated
  - [x]  Version keys have new version
  - [ ]  Update of “Latest” commits cherry-picked into release branch
- [x]  Release commits pulled into spreadsheet
- [x]  Release notes doc created
- [x]  Call for release notes made in Slack

# Release Testing
## Microbenchmark
- [x] Test passing
- [x]  Results added to release/release_logs
## Long Running Tests (mark complete when run 24 hrs no issues)
- [x] actor_deaths
- [x]  apex
- [x]  impala
- [x]  many_actor_tasks
- [ ]  many_drivers
- [ ]  many_ppo
- [x]  many_tasks_serialized_ids
- [x]  many_tasks
- [x]  node_failures
- [x]  pbt
- [x]  serve_failure
- [x]  serve
## Long Running Distributed Tests
- [x] pytorch_pbt_failure
- [x]  horovod_test
## Stress Tests
- [x]    test_dead_actors
  - [x]    succeeds
  - [x]    Results added to release/release_logs
- [x]    test_many_tasks
  - [x]    succeeds
  - [x]    Results added to release/release_logs
- [x]    test_placement_group
  - [x] succeeds
  - [x]  Results added to release/release_logs

## RLlib Tests
- [x] regression_tests
- [x]  compact-regression-tests-tf
  - [x]  succeeds
  - [x]  Results added to release/release_logs
- [x]  compact-regression-tests-torch
  - [x]  succeeds
  - [x]  Results added to release/release_logs
- [x]  stress_tests
- [x]  unit_gpu_tests
## Scalibility Envelope
- [ ]  Scalability Envelope Tests
## ASAN
- [x]  ASAN Test
## K8s Test
- [x]  K8s cluster launcher test
- [x]  K8s operator test
## Data processing tests
- [x] streaming_shuffle
- [x]  dask on ray test
## Tune tests
- [x] test_bookkeeping_overhead
- [x]  test_result_throughput_cluster (ignore final time)
- [x]  test_result_throughput_single_node (ignore final time)
- [x]  test_network_overhead (ignore final time)
- [x]  test_long_running_large_checkpoints
- [x]  test_xgboost_sweep
- [x]  test_durable_trainable
## XGBoost Tests
- [x]  distributed_api_test
- [x]  train_small
- [x]  train_moderate
- [x]  train_gpu
- [x]  tune_small
- [x]  tune_4x32
- [x]  tune_32x4
- [x]  ft_small_non_elastic
- [x]  ft_small_elastic
# Final Steps
- [x] Wheels uploaded to Test PyPI
- [ ]  Wheel sanity checks with Test PyPI
- [ ]  Windows
  - [ ]  Python 3.6
  - [ ]  Python 3.7
  - [ ]  Python 3.8
- [ ]  OSX
  - [ ]  Python 3.6
  - [ ]  Python 3.7
  - [ ]  Python 3.8
- [ ]  Linux
  - [ ]  Python 3.6
  - [ ]  Python 3.7
  - [ ]  Python 3.8
- [ ] Release is created on Github with release notes
- [ ]  Release includes contributors
- [ ]  Release notes sent for review to team leads
- [ ]  Release is published
- [ ]  Wheels uploaded to production PyPI
- [ ]  Installing latest with pip install -U ray reveals correct version number and commit hash
- [x]  “Latest” docs point to new release version
- [ ]  Docker image latest is updated on dockerhub
- [ ]  PR to bump master version is merged
- [ ]  Release is announced internally
- [ ]  Release is announced externally
- [ ]  Any code/doc changes made during the release process contributed back to master branch

**Comment by sonnysideup** [comment]
I just noticed there's a 1.3 release on Docker hub but no GitHub release w/ notes. How exactly does this release process work?

**Comment by amogkam** [comment]
@sonnysideup the release is not official until the Github release is made and the new wheels are published on Pypi. I think the 1.3 on Docker hub is using this branch? cc @ijrsvt can you confirm how this works with the Ray Docker images?

**Comment by ijrsvt** [comment]
The `1.3` images are built automatically with each commit to the 'release branch'. The `latest` tagged images do not alias to `1.3` until the GitHub release happens.

**Comment by jovany-wang** [comment]
@richardliaw  How about that adding releasing Java version as a work item from next version?
