### ISSUE TITLE
[tune/autoscaler] Usability issues

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#1577]
Here are some general list of complaints for usability. @vlad17 @ericl @concretevitamin - feel free to add more or +1 or demote entries.

[Autoscaler]
 - [x] Provide a sugared call to ssh into cluster? Addressed in #2560 
 - [ ] Supporting environment variables and conda environments elegantly
    - Consider making all shell commands a single file so that env variables only need to be set once.
    - Add note about Conda environments in the example.yaml
 - [x] Have some faster way of porting my development env to my cluster AFTER I've started it without restarting or rerunning setup commands. Addressed in #2560.
 
[Tune]
 - [ ] Automatically starting a tensorboard server? 
    - Punting for now
 - [x] It should be a lot easier to create a single trial. Right now, there's no way to do that. - Addressed with `create_trial_from_config` in #2452.
 - What is the user experience for recovering from a trial checkpoint? what if the tune process dies?  #2840.

[General]
 - [ ] Fractional GPU Support (#2768, Need to add documentation)
 - [x] Debugging logs for when ray fails

**Comment by vlad17** [comment]
@atumanov wanted to start a doc for this. I think he has some good points about taking the abstract sugared stuff that I want and offering small components that are much cleaner API wise that I can then use (start cluster, run experiment, sync data?)

**Comment by richardliaw** [comment]
Oh yeah; it'd be great to get some of that conversation here so we can reference as we create issues!

**Comment by robertnishihara** [comment]
I've had issues with starting large clusters. As far as I can recall, I've never been able to start a 200 or 300 node cluster with the autoscaler. It often has a problem after 50 or 60.

**Comment by concretevitamin** [comment]
I was imagining something like the following
```
$ ray create_or_update <config file, detailing my binary/script to upload and run>
... <launch cluster, do some work>
...
...
Your cluster is ready:
  head - ip.ip.ip.ip
  tensorboard - ip.ip.ip.ip
TensorFlow log dir:
  rsync -Pavr --progress <you>@ip.ip.ip.ip:log/dir ./local_dir
```
So people can just copy the address in `tensorboard - ip.ip.ip.ip`, open it in local browser, and watch the training.

**Comment by richardliaw** [comment]
I was thinking it might also be nice to have a separate functionality to do experiment launching.

You might have a bunch of files you want to edit and such, and an entrypoint from which your experiment starts. This simple model doesn't always fit nicely in the separation of `setup_commands` or `start_ray_commands`. ie; you might want `setup_commands` to install and start docker, but `start_ray_commands` is going to be executed inside docker. Putting `ray start` in `setup_commands` will cause you do start ray every time you want to execute that block of commands.

 If you don't want ray to restart; you need to put your entry point in `setup_commands` and `start_ray` separately, but this script isn't when you're starting a cluster.

It would make sense to have a separate `experiment.yaml` or something, where you can list all file directories, an entry point, and (optionally) an existing docker container, and `ray execute experiment.yaml` can be run over and over again without restarting or rerunning ray/install commands.

**Comment by richardliaw** [comment]
Closing as these have been split into individual issues (addressed over the course of half a year...)
