### ISSUE TITLE
[Release] 1.4 Checklist (Target date June 1)

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/ray#15975]
# Initial Steps
- [x]  Announced branch cut date and estimated release date

# Branch Cut
- [x]  Release branch created
- [x]  Release branch versions updated
- [x]  Release commits pulled into spreadsheet
- [x]  Release notes doc created
- [x]  Call for release blockers and release notes made in email and Slack
  - [x]  Messaged Ant about release blockers

# Release Testing
## Microbenchmark
@ray-project/ray-core (@clarkzinzow )

- [x] Test passing
- [x] Results added to release/release_logs

## Long Running Tests (mark complete when run 24 hrs no issues)
- [x] actor_deaths
- [x]  apex
- [x]  impala
- [x]  many_actor_tasks
- [x]  many_drivers
- [x]  many_ppo
- [x]  many_tasks_serialized_ids
- [x]  many_tasks
- [x]  node_failures (@ray-project/ray-core)
- [x]  pbt
- [x]  serve_failure (Serve team @simon-mo )
- [x]  serve (Serve team @simon-mo )

## Long Running Distributed Tests
- [x] pytorch_pbt_failure (@richardliaw - many warning messages from syncing but nonfatal )
- [x] horovod_test (skip since this didn't pass on 1.3 either)

## Stress Tests
@clarkzinzow - BLOCKED on placement groups.

- [ ]  test_dead_actors
  - [x]  succeeds
  - [x]  Results added to release/release_logs
- [ ]  test_many_tasks
  - [x]  succeeds
  - [x]  Results added to release/release_logs
- [x]  test_placement_group
  - [ ]  succeeds
  - [ ]  Results added to release/release_logs
  - [x] Non-blocker
## RLlib Tests
- [x] regression_tests
- [x] compact-regression-tests-tf
  - [x] succeeds
  - [x] Results added to release/release_logs
- [x] compact-regression-tests-torch
  - [x] succeeds
  - [x] Results added to release/release_logs
- [x] stress_tests
- [x] unit_gpu_tests

## Serve Distributed Test
- [x] Scaling up test (@simon-mo)

## Scalability Envelope
- [x]  Scalability Envelope Tests (@clarkzinzow )
- [x]  Results added to release/release_logs

## ASAN
- [x]  ASAN Test 

## K8s Test
- [x]  K8s operator tests (@DmitriGekhtman )

## Data processing tests
@rkooo567 
- [x] streaming_shuffle
- [x] dask on ray test
- [x] Results added to release/release_logs
## Tune tests
- [x] test_bookkeeping_overhead
- [x] test_result_throughput_cluster (ignore final time)
- [x] test_result_throughput_single_node (ignore final time)
- [x] test_network_overhead (ignore final time)
- [x] test_long_running_large_checkpoints (running)
- [x] test_xgboost_sweep
- [x] test_durable_trainable
- [ ] Results added to release/release_logs
## XGBoost Tests
- [x]  distributed_api_test
- [x]  train_small
- [x]  train_moderate
- [x]  train_gpu
- [x]  tune_small
- [x]  tune_4x32
- [x]  tune_32x4
- [x]  ft_small_non_elastic
- [x]  ft_small_elastic
# Final Steps
- [x] Release is created on Github with release notes
- [x]  Release notes sent for review to team leads
- [x]  Release includes contributors
- [x]  Release is published
- [x] Wheels uploaded to Test PyPI
- [x]  Wheel sanity checks with Test PyPI
- [ ]  Windows
  - [ ]  Python 3.6
  - [ ]  Python 3.7
  - [ ]  Python 3.8
- [x]  OSX
  - [x]  Python 3.6
  - [x]  Python 3.7
  - [x]  Python 3.8
- [ ]  Linux
  - [ ]  Python 3.6
  - [ ]  Python 3.7
  - [ ]  Python 3.8
- [x]  Wheels uploaded to production PyPI
- [x]  Installing latest with pip install -U ray reveals correct version number and commit hash
- [x]  “Latest” docs point to new release version
- [x]  Docker image latest is updated on dockerhub
- [ ]  PR to bump master version is merged
- [ ]  Release is announced internally
- [ ]  Release is announced externally
- [ ]  Any code/doc changes made during the release process contributed back to master branch
