### ISSUE TITLE
ConcurrencyGroup Proposal

### ISSUE THREAD

**Issue by jovany-wang** [ray-project/ray#16047]
We'd like to isolate different actor methods to different threads.

V2 API Proposal is here: https://docs.google.com/document/d/1KOOzEZXClsUZ_8Kjp37RIqT-9_-MSogFd4RcCsfVvsc/edit#

If you'd like to take looks at the motivation, background and the discussions before, please refer to the initial doc:
https://docs.google.com/document/d/1OLI_BsUUJrhW3vGRJVjwSs3rIS3I0-746Wuf2d4mEow/edit?usp=sharing

TODOs
- [x] Support Java API & core implementation https://github.com/ray-project/ray/pull/16795
- [x] Support Java local mode #18241
- [x] Support Python API with asyncio #18567
- [ ] Cross language support.
- [ ] Support Pyhton threaded API  (No plan to support yet.)
- [x] Add documents #21600
- [x] Static definition support. #19793  #20373
- [x] Abstract PoolManager and FiberStateManager. #20467
- [ ] Change setMaxConcurrency API semantics

**Comment by jovany-wang** [comment]
As discussed before, `ConcurrentGroup`  is a better name.

**Comment by jovany-wang** [comment]
@pcmoritz @ericl for the API approval.

**Comment by jovany-wang** [comment]
@ericl  Can the V2 API be approved now? 
The initial implementation based on the V1 API is here https://github.com/ray-project/ray/pull/16795
Once the V2 API is approved, this PR can be moved forward.

**Comment by ericl** [comment]
I made some comments on the doc.

**Comment by jovany-wang** [comment]
> I made some comments on the doc.

Thanks. All comments look good to me.  Accepted.

**Comment by ericl** [comment]
It LGTM. @pcmoritz any other thoughts?

**Comment by jovany-wang** [comment]
Hi @raulchen @ericl @kfstorm , since most of items were done, I'm proposing that add the API `options(default_max_concurrency_=10)` and mark `options(max_concurrency=10)` as deprecated.

Because in fact, it's under the default concurrency group indeed.
