### ISSUE TITLE
[Datasets] Docs polish and UX audit tracker

### ISSUE THREAD

**Issue by wuisawesome** [ray-project/ray#18262]
- [x] Create a `pip install ray[data]` extras, with all the optional dependencies.
- [x] Quick link index to APIs
- [x] Polish error messages (#18171 ) (explain why workers are dying).
- [x] Make fsspec an optional import
- [x] Add documentation to surrounding Ray ecosystem docs pointing at Ray Datasets (e.g. data loading for pytorch)
- [x] Make it clear in the docs for `DatasetPipeline.split()` and `DatasetPipeline.split_at_indices()`, and maybe in the logged warning message, that post-split pipelines must be consumed in parallel and that blocking on consuming a single shard will hang forever.
- [x] Docs on Datasets compute model, and what happens "under-the-hood" when creating or manipulating a `Dataset` or `DatasetPipeline`.
- [x] Make compatibility matrix `read_*`, `from_*`, and `to_*` API calls link to the corresponding API reference docs.
- [x] #21962
- [x] https://github.com/ray-project/ray/issues/17775
- [ ] Highlight pandas interop (explicit examples w/ pandas)
- [ ] Docs on sharding/IO (why we create directory instead of single file)
- [ ] Change write args to `root_path` or `root_dir`, warning if directory ends in `.csv`
- [ ] Better error on `__get_item__` operation
- [ ] Add nightly test for nyc taxi dataset IO perf
- [ ] TODO repro nyc taxi dataset issue (@worldveil ) 
- [ ] Examples of transforming tabular data
- [ ] Document that `batch_size` in `.map_batches()` doesn't limit working set size, that windowing should be used instead for that.
- [ ] .to_torch()/.to_tf() naming → to_torch_dataset()/to_tensorflow_dataset()
- [ ] Mention that datasets aren't indexed in the docs
- [ ] Explicitly note that column selection isn't possible on Datasets, funnel users to batch mapping for columnar transformations and aggregation API for columnar aggregations.
- [ ] Need better docs for `.map()` and `.map_batches()`, indicating that the former is for row-based mapping, the latter is for batch-based mapping (i.e. vectorized column operations and the like). Should be clear how data scientist users can map pandas operations in distributed way.
- [ ] Better progress reporting for I/O methods, users frequently encounter what they think are "hangs" when the work is in progress.
- [ ] Filesystem arg for I/O APIs: we should add top-level examples for (1) reading from private cloud storage with specified credentials, (2) reading from GCS and Azure Blob Storage. Also, the API documentation can also be improved to indicate that both Arrow filesystems and fsspec filesystems are accepted, and that these filesystems can be used to specify things like credentials, regions/zones, projects, etc.
- [ ] Make `DatasetPipeline` API editor-friendly: https://github.com/ray-project/ray/issues/20888
- [ ] Follow strict semantics about row/partition reordering, and document them: https://github.com/ray-project/ray/issues/20329
- [x] https://github.com/ray-project/ray/issues/22084
- [ ] Make the simple and Arrow dataset distinction more clear, including: (a) what are the differences, (b) what makes a dataset simple vs. Arrow (method of creation, outputs of mappers, etc.), (c) examples of (a) and (b).
- [ ] #22411 
- [ ] Allow user to set output column names for aggregation results.

**Comment by worldveil** [comment]
Maybe add:

- Code example of loading into dataframe (dask? modin?)
- Code example of performing transforms, creating new columns to get ready for training

**Comment by worldveil** [comment]
Also, a progress bar or some indication that downloading is happening?

**Comment by clarkzinzow** [comment]
Copy from a Slack message I sent to a user about the compute model:

When creating a `Dataset` via reading data from storage,
```python
ds = ray.data.read_parquet(s3_url, parallelism=20)
```
we’ll eventually create `parallelism` read tasks, but the reads are initially lazy: we’ll kick off one read task immediately, but will only start the other `parallelism - 1` read tasks when ds starts getting consumed, either by the end-user
```python
for row in ds.iter_rows():
    print(row)
```
or by a downstream operation, like a map
```python
ds = ds.map_batches(lambda x: x + 1)
```
These read tasks will ramp up exponentially, e.g.
1. We start with 1 read task to produce the first block.
2. When something downstream (like `.map_batches()`) tries to consume the second block, it kicks off the read task for the second block.
3. When something downstream ties to consume the third block, it kicks off the read task for the third and fourth block.
4. When something downstream tries to consume the 5th block, it kicks off the read task for the 5th - 8th blocks.
5. And so on, up to the 20th read task and block.
Right now, the read stage is the only lazy stage in Datasets; everything downstream of the read stage is eagerly computed and blocking.
```python
# This is lazy; it returns before all data is read.
ds = ray.data.read_parquet(s3_url, parallelism=20)
# This is eager; it will submit all map tasks
# and block until they are done.
ds = ds.map_batches(lambda x: x + 1)
# This is also eager.
ds = ds.random_shuffle()
```
A general exception to that is if you create a `DatasetPipeline`, which [allows you to pipeline](https://docs.ray.io/en/master/data/dataset-pipeline.html) stages of computation across groups of datasets, such that those lazily composed computation stages aren’t triggered until you start consuming the data via e.g. `pipe.iter_batches()` or the like.

The underlying compute for transformations such as `.map()`, `.map_batches()`, `.filter()`, etc., uses normal Ray tasks by default, but can use an autoscaling actor pool if you specify compute="actors"; the docs have a batch inference example that uses the actor compute model: https://docs.ray.io/en/master/data/dataset.html#transforming-datasets

**Comment by ericl** [comment]
Closing this issue. Please file individual tickets for tracking instead of batch issues.
