### ISSUE TITLE
[Tracker] Flaky tests

### ISSUE THREAD

**Issue by czgdp1807** [ray-project/ray#19800]
I am opening this issue to easily track things regarding flaky tests. As of now I am investigating the following ones,

- [ ] `test_client_reconnect.py` - https://github.com/ray-project/ray/pull/19580 - The `test_noisy_puts` passes on my machine multiple times though fails on CI. It is important to re-produce it locally at least once so that we can figure how to fail everytime for debugging it thoroughly. 
- [x] `test_basic.py::test_ray_options` - https://github.com/ray-project/ray/pull/19832 - In this test I observed that sometimes resource availability is changed and sometimes not. The reason I figured out is that `time.sleep(0.1)` is unreliable on Windows. It doesn't always ensure that resource availability will change. So, instead of doing that we should either give it a longer period of sleep time but again that's non-deterministic and non-robust. Other way is to keep requesting `ray.available_resources` for large number of times along with sleep in each iteration. This will reduces the chances of failures (it starts passing on my system at least). See the reference to code and diff below.

https://github.com/ray-project/ray/blob/aa5499ef0fc141f01db52df133a5b473d5f82fab/python/ray/tests/test_basic.py#L301-L326

```diff
diff --git a/python/ray/tests/test_basic.py b/python/ray/tests/test_basic.py
index c3b515aa7..b56f94049 100644
--- a/python/ray/tests/test_basic.py
+++ b/python/ray/tests/test_basic.py
@@ -306,8 +306,22 @@ def test_ray_options(shutdown_only):
     def foo():
         import time
         # Sleep for a heartbeat period to ensure resources changing reported.
-        time.sleep(0.1)
-        return ray.available_resources()
+        to_check = ["CPU", "GPU", "memory", "custom1"]
+        resources = ray.available_resources()
+        updated = ray.available_resources()
+        itr = 0
+        while itr < 1000:
+            time.sleep(0.1)
+            updated = ray.available_resources()
+            do_return = True
+            for key in to_check:
+                if resources[key] == updated[key]:
+                    do_return = False
+                    break
+            if do_return:
+                return updated
+            itr += 1
+        return updated

     without_options = ray.get(foo.remote())
     with_options = ray.get(
```
- [x] `test_cancel::test_comprehensive` - The following test fails due to timing out of the second statement. However, when the limit is bumped from 10 to 30 it starts passing. So, I want to know whether to make a PR with a bump in timeout limit or investigate further  why this thing is slow.

https://github.com/ray-project/ray/blob/39486ef08c8a527031d554ac8da39ebe079901f7/python/ray/tests/test_cancel.py#L147-L154

```diff
diff --git a/python/ray/tests/test_cancel.py b/python/ray/tests/test_cancel.py
index b51d31895..beae8c2c9 100644
--- a/python/ray/tests/test_cancel.py
+++ b/python/ray/tests/test_cancel.py
@@ -150,7 +150,7 @@ def test_comprehensive(ray_start_regular, use_force):
         ray.get(a, timeout=10)

     with pytest.raises(valid_exceptions(use_force)):
-        ray.get(a2, timeout=10)
+        ray.get(a2, timeout=30)

     signaler.send.remote()
```
- [ ] `test_standalone.py::test_serve_shutdown` - Passes on my Windows system several times.
- [ ] `test_multinode_failures_2.py::test_actor_creation_node_failure[ray_start_cluster0]` - Passes on my Windows system several times.
- [ ] `test_scheduling.py::test_locality_aware_leasing_borrowed_objects` - Reproduced only once. Investigating. Will try to make it deliberately fail. 
- [ ] `test_multinode_failures_2.py::test_object_reconstruction` - Can I work on this? It seems like we need to implement object reconstruction in plasma. 

https://github.com/ray-project/ray/blob/0a5942d8b043bf01ffb7356bfa513234f775ee7f/python/ray/tests/test_multinode_failures_2.py#L12-L28

Latest logs:

```python
>                       raise value.as_instanceof_cause()
E                       ray.exceptions.RayTaskError: ray::g() (pid=11516, ip=127.0.0.1)
E                         File "python\ray\_raylet.pyx", line 587, in ray._raylet.execute_task
E                           with core_worker.profile_event(b"task:deserialize_arguments"):
E                         File "python\ray\_raylet.pyx", line 609, in ray._raylet.execute_task
E                           raise_if_dependency_failed(arg)
E                         File "python\ray\_raylet.pyx", line 441, in ray._raylet.raise_if_dependency_failed
E                           raise arg
E                       ray.exceptions.ReferenceCountingAssertionError: Failed to retrieve object ffffffffffffffffffffffffffffffffffffffffffffffffffffffff. To see information about where this ObjectRef was created in Python, set the environment variable RAY_record_ref_creation_sites=1 during `ray start` and `ray.init()`.
E
E                       The object has already been deleted by the reference counting protocol. This should not happen.

python\ray\worker.py:1643: RayTaskError
```
- [x] `test_basic_3.py::test_worker_startup_count` - Reproduced. Logs below. Seems familiar to me from `cv_.wait_for_` bug. I will investigate this.

```
―――――――――――――――――――――――――――――――――― test_worker_startup_count ―――――――――――――――――――――――――――――――――――

ray_start_cluster = <ray.cluster_utils.Cluster object at 0x000001709B89E5E0>

    def test_worker_startup_count(ray_start_cluster):
        """Test that no extra workers started while no available cpu resources
        in cluster."""

        cluster = ray_start_cluster
        # Cluster total cpu resources is 4.
        cluster.add_node(
            num_cpus=4, _system_config={
                "debug_dump_period_milliseconds": 100,
            })
        ray.init(address=cluster.address)

        # A slow function never returns. It will hold cpu resources all the way.
        @ray.remote
        def slow_function():
            while True:
                time.sleep(1000)

        # Flood a large scale lease worker requests.
        for i in range(10000):
            # Use random cpu resources to make sure that all tasks are sent
            # to the raylet. Because core worker will cache tasks with the
            # same resource shape.
            num_cpus = 0.24 + np.random.uniform(0, 0.01)
            slow_function.options(num_cpus=num_cpus).remote()

        # Check "debug_state.txt" to ensure no extra workers were started.
        session_dir = ray.worker.global_worker.node.address_info["session_dir"]
        session_path = Path(session_dir)
        debug_state_path = session_path / "debug_state.txt"

        def get_num_workers():
            with open(debug_state_path) as f:
                for line in f.readlines():
                    num_workers_prefix = "- num PYTHON workers: "
                    if num_workers_prefix in line:
                        num_workers = int(line[len(num_workers_prefix):])
                        return num_workers
            return None

        # Wait for "debug_state.txt" to be updated to reflect the started worker.
        start = time.time()
>       wait_for_condition(lambda: get_num_workers() == 16)

python\ray\tests\test_basic_3.py:285:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

condition_predictor = <function test_worker_startup_count.<locals>.<lambda> at 0x000001709BBD9F70>
timeout = 10, retry_interval_ms = 100, kwargs = {}, start = 1635873928.8510194

    def wait_for_condition(condition_predictor,
                           timeout=10,
                           retry_interval_ms=100,
                           **kwargs: Any):
        """Wait until a condition is met or time out with an exception.

        Args:
            condition_predictor: A function that predicts the condition.
            timeout: Maximum timeout in seconds.
            retry_interval_ms: Retry interval in milliseconds.

        Raises:
            RuntimeError: If the condition is not met before the timeout expires.
        """
        start = time.time()
        while time.time() - start <= timeout:
            if condition_predictor(**kwargs):
                return
            time.sleep(retry_interval_ms / 1000.0)
>       raise RuntimeError("The condition wasn't met before the timeout expired.")
E       RuntimeError: The condition wasn't met before the timeout expired.
```
- [x] `tests:test_basic_3_client_mode` - Reproduced. Log below.
```python
================================== FAILURES===================================
__________________________ test_worker_startup_count __________________________

ray_start_cluster = <ray.cluster_utils.Cluster object at 0x0000027F431D4730>

    def test_worker_startup_count(ray_start_cluster):
        """Test that no extra workers started while no available cpu resources
        in cluster."""
    
        cluster = ray_start_cluster
        # Cluster total cpu resources is 4.
        cluster.add_node(
            num_cpus=4, _system_config={
                "debug_dump_period_milliseconds": 100,
            })
        ray.init(address=cluster.address)
    
        # A slow function never returns. It will hold cpu resources all the way.
        @ray.remote
        def slow_function():
            while True:
                time.sleep(1000)
    
        # Flood a large scale lease worker requests.
        for i in range(10000):
            # Use random cpu resources to make sure that all tasks are sent
            # to the raylet. Because core worker will cache tasks with the
            # same resource shape.
            num_cpus = 0.24 + np.random.uniform(0, 0.01)
            slow_function.options(num_cpus=num_cpus).remote()
    
        # Check "debug_state.txt" to ensure no extra workers were started.
        session_dir = ray.worker.global_worker.node.address_info["session_dir"]
        session_path = Path(session_dir)
        debug_state_path = session_path / "debug_state.txt"
    
        def get_num_workers():
            with open(debug_state_path) as f:
                for line in f.readlines():
                    num_workers_prefix = "- num PYTHON workers: "
                    if num_workers_prefix in line:
                        num_workers = int(line[len(num_workers_prefix):])
                        return num_workers
            return None
    
        # Wait for "debug_state.txt" to be updated to reflect the started worker.
        start = time.time()
>       wait_for_condition(lambda: get_num_workers() == 16)

\\?\C:\conda_tmp\Bazel.runfiles_o3rh_htd\runfiles\com_github_ray_project_ray\python\ray\tests\test_basic_3.py:285: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

condition_predictor = <function test_worker_startup_count.<locals>.<lambda> at 0x0000027F431DB160>
timeout = 10, retry_interval_ms = 100, kwargs = {}, start = 1635876846.3765578

    def wait_for_condition(condition_predictor,
                           timeout=10,
                           retry_interval_ms=100,
                           **kwargs: Any):
        """Wait until a condition is met or time out with an exception.
    
        Args:
            condition_predictor: A function that predicts the condition.
            timeout: Maximum timeout in seconds.
            retry_interval_ms: Retry interval in milliseconds.
    
        Raises:
            RuntimeError: If the condition is not met before the timeout expires.
        """
        start = time.time()
        while time.time() - start <= timeout:
            if condition_predictor(**kwargs):
                return
            time.sleep(retry_interval_ms / 1000.0)
>       raise RuntimeError("The condition wasn't met before the timeout expired.")
E       RuntimeError: The condition wasn't met before the timeout expired.

c:\users\gagan\ray_project\ray\python\ray\_private\test_utils.py:309: RuntimeError
```
Extra info,
```
[2m[1m[33m(scheduler +3m56s)[0m Warning: The following resource request cannot be scheduled right now: {'CPU': 0.2489}. This is likely due to all cluster resources being claimed by actors. Consider creating fewer actors or adding more nodes to this Ray cluster.

[2m[1m[33m(scheduler +3m56s)[0m Warning: The following resource request cannot be scheduled right now: {'CPU': 0.2486}. This is likely due to all cluster resources being claimed by actors. Consider creating fewer actors or adding more nodes to this Ray cluster.
... so on
```
```
2021-11-02 18:34:17,823	INFO worker.py:838 -- Connecting to existing Ray cluster at address: 127.0.0.1:6379
2021-11-02 18:34:18,680	WARNING worker.py:1239 -- The actor or task with ID 2d2ea8c44e9bfe84b676f6fe58ea2d9105623da94d8c1054 cannot be scheduled right now. You can ignore this message if this Ray cluster is expected to auto-scale or if you specified a runtime_env for this actor or task, which may take time to install.  Otherwise, this is likely due to all cluster resources being claimed by actors. To resolve the issue, consider creating fewer actors or increasing the resources available to this Ray cluster.
Required resources for this actor or task: {CPU: 0.240800}
Available resources on this node: {3.263900/4.000000 CPU, 496144320.019531 GiB/496144320.019531 GiB memory, 7680000.000000 GiB/7680000.000000 GiB object_store_memory, 1.000000/1.000000 node:127.0.0.1}
 In total there are 84 pending tasks and 0 pending actors on this node.
============================== warnings summary ===============================
C:\ProgramData\Anaconda3\envs\ray_dev\lib\site-packages\_pytest\config\__init__.py:935
  C:\ProgramData\Anaconda3\envs\ray_dev\lib\site-packages\_pytest\config\__init__.py:935: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: anyio
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
```
- [ ] `test_chaos::test_chaos_task_retry` - Fails consistently on Windows.

```python
―――――――――――――― ERROR at setup of test_chaos_task_retry[ray_start_chaos_cluster0] ―――――――――――――――

request = <FixtureRequest for <Function test_chaos_task_retry[ray_start_chaos_cluster0]>>

    def fill(request):
        item = request._pyfuncitem
        fixturenames = getattr(item, "fixturenames", None)
        if fixturenames is None:
            fixturenames = request.fixturenames

        if hasattr(item, 'callspec'):
            for param, val in sorted_by_dependency(item.callspec.params, fixturenames):
                if val is not None and is_lazy_fixture(val):
                    item.callspec.params[param] = request.getfixturevalue(val.name)
                elif param not in item.funcargs:
>                   item.funcargs[param] = request.getfixturevalue(param)

c:\programdata\anaconda3\envs\ray_dev\lib\site-packages\pytest_lazyfixture.py:37:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
python\ray\tests\conftest.py:436: in ray_start_chaos_cluster
    ray.init("auto")
python\ray\_private\client_mode_hook.py:105: in wrapper
    return func(*args, **kwargs)
python\ray\worker.py:833: in init
    redis_address, _, _ = services.validate_redis_address(address)
python\ray\_private\services.py:375: in validate_redis_address
    address = find_redis_address_or_die()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    def find_redis_address_or_die():

        redis_addresses = find_redis_address()
        if len(redis_addresses) > 1:
            raise ConnectionError(
                f"Found multiple active Ray instances: {redis_addresses}. "
                "Please specify the one to connect to by setting `address`.")
            sys.exit(1)
        elif not redis_addresses:
>           raise ConnectionError(
                "Could not find any running Ray instance. "
                "Please specify the one to connect to by setting `address`.")
E           ConnectionError: Could not find any running Ray instance. Please specify the one to connect to by setting `address`.

python\ray\_private\services.py:286: ConnectionError
```

**Comment by czgdp1807** [comment]
`test_multinode_failures_2.py::test_object_reconstruction` - Can I work on this? It seems like we need to implement object reconstruction in plasma. Github snippet referred in OP. Let me know.

**Comment by czgdp1807** [comment]
Just dropping in:

To reproduce flaky tests locally, shift the test inside a nested function. In the parent test function, call the newly created one 100-200 times and it will fail at least once. For example see below,

```python
def test_locality_aware_leasing_borrowed_objects(ray_start_cluster):
    # This test ensures that a task will run where its task dependencies are
    # located, even when those objects are borrowed.
    cluster = ray_start_cluster

    # Disable worker caching so worker leases are not reused, and disable
    # inlining of return objects so return objects are always put into Plasma.
    cluster.add_node(
        num_cpus=1,
        resources={"pin_head": 1},
        _system_config={
            "worker_lease_timeout_milliseconds": 0,
            "max_direct_call_object_size": 0,
        })
    # Use a custom resource for pinning tasks to a node.
    worker_node = cluster.add_node(num_cpus=1, resources={"pin_worker": 1})
    ray.init(address=cluster.address)

    def test_util(): # Called 100 times below, the failure reproduced once.

        @ray.remote
        def f():
            return ray.worker.global_worker.node.unique_id

        @ray.remote
        def g(x):
            return ray.get(h.remote(x[0]))

        @ray.remote
        def h(x):
            return ray.worker.global_worker.node.unique_id

        # f will run on worker, f_obj will be pinned on worker.
        f_obj = f.options(resources={"pin_worker": 1}).remote()
        worker_node_output_id = ray.get(g.options(resources={
            "pin_head": 1
        }).remote([f_obj]))
        # g will run on head, f_obj will be borrowed by head, and we confirm that
        # h(f_obj) is scheduled onto worker, the node that has f_obj.
        assert worker_node_output_id == worker_node.unique_id
    
    for _ in range(100):
        test_util()
```

**Comment by wuisawesome** [comment]
> Let me know.

Conclusion from the meeting: we'll hold off from now since it's a multi node issue.

**Comment by czgdp1807** [comment]
Updated OP with the status of `test_basic_3` and `test_basic_3_client_mode`. Both timeout on my system. I recently opened a PR for timing out of `test_fair_qeueing` - https://github.com/ray-project/ray/pull/19456. There I bumped the timeout limit for Windows from 60s to 510s after which it started working fine. Bazel's limit is still 300s so tests after `test_fair_qeueing` are not reached. I commented this and then `test_worker_startup_count` whose information is in the OP. I will investigate this now.

**Comment by mattip** [comment]
Can you compare the logs from a windows run in %TEMP%/ray/session_latest to the logs in a linux run in /tmp/ray/session_latest of one of the slowest tests to see what is taking so much time? I think 8x slower is a bit extreme.

**Comment by czgdp1807** [comment]
Sure. I can do the testing on Linux tomorrow. Yes 8x time taken is slow though the behaviour is same in every run. So, probably my Windows is slow. But still I will do the Linux testing tomorrow to be double sure.

**Comment by mattip** [comment]
I wonder if you could get a similar virtual machine running linux to be able to fairly compare the results.

**Comment by czgdp1807** [comment]
Regarding, `test_basic_3::test_worker_startup_count`, the `debug_state.txt` takes 23.29ish seconds (on multiple runs on my machine). However, `wait_for_condition` (see below) has a default argument `timeout=10`. Hence, the test times out. So a simple fix and high level fix would be to bump the time limit from 10s to 25 or higher (if we want to be safe everywhere). cc: @wuisawesome @pcmoritz 

https://github.com/ray-project/ray/blob/9385b6c1be97b25a31bcc475f8c6ee5b2e1a2455/python/ray/tests/test_basic_3.py#L285

**Comment by mattip** [comment]
That seems painfully slow. Maybe another option would be to reduce the number of workers/tasks on windows

**Comment by pcmoritz** [comment]
So I'd say spend some time to investigate the performance issue. If we can identify it great, if we can fix it even better. If we can't or it would take too much time, bumping the timeout seems fine.

A reasonable time to spend on this would be about a day I'd say, if it needs longer let's reconsider.

**Comment by czgdp1807** [comment]
> A reasonable time to spend on this would be about a day I'd say, if it needs longer let's reconsider.

Sure. I will get back to you by tomorrow after noon. I am tracing the code block which consuming the most time. May be that can help us determine where the bottleneck lies.

**Comment by czgdp1807** [comment]
Regarding the performance of test_worker_startup_count on Windows, I traced the code path and found that, [this line](https://github.com/ray-project/ray/blob/4cb23d1c95635974efbb68bc3edcdefbe6e5d83b/src/ray/raylet/main.cc#L293) consumes most of the time. The implementation of `run` method is from `boost::asio::io_context` as far as I can figure out. So, I think the time taken for this depends mostly on third party libraries. Hence, IMO, bumping the time limit is the easiest way to make this test pass on Windows.

**Comment by pcmoritz** [comment]
The fact that most time is spent in `main_service.run();` is expected since the call is blocking and will basically wait until the raylet shuts down (which is the duration of the Ray worker being up). So the real performance difference between windows and linux must come from somewhere else.

**Comment by czgdp1807** [comment]
> So the real performance difference between windows and linux must come from somewhere else.

Should we investigate more if it's coming from somewhere due to Ray's code. Yeah, `run` is taken from `boost` but may be that thing is calling some other Ray code. If that's so then let me know, I can dig a bit more to find out which code is responsible for the slowdown in Windows. Bumping time limit is based on the fact, this test is out of our scope and the performance slow down is due to some third party dependencies.

**Comment by czgdp1807** [comment]
@pcmoritz @wuisawesome I am able to reproduce, `test_chaos::test_chaos_task_retry` (logs in the last point in OP). Can I work on this? Thought of asking as it appears to be a new test, so may be the work is already going on to fix this?

**Comment by pcmoritz** [comment]
@czgdp1807 Working on unskipping some of the non multi-node tests in https://github.com/ray-project/ray/pull/20212/files would be higher priority I think.

For now you can skip the `test_chaos::test_chaos_task_retry`. It is also a multi-node test :)

**Comment by czgdp1807** [comment]
Great. Thanks for pointing me to the file. It will be easier to look for new tests to work on.
