### ISSUE TITLE
[Feature] Plan to improve `RayActorDiedError`.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#20534]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Status quo
`RayActorDiedError` is an infamously bad error message known in Ray. 

When you call `ray.get` on actor method, `RayActorDiedError` is raised when something goes wrong. The problem is that the error message doesn't have any information regarding it. This is the current error message.

```
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
```

This is bad because
- The error doesn't indicate what to do (next action item).
- The error doesn't say anything about why the actor is dead.

### Problem
What is missing now? 

1. Currently, when the actor dies, we don't store any information regarding why it dies. 
2. Currently, Ray stores an "error object" when something goes wrong. Error object is a small lightweight object that only contains metadata, which indicates the error type. For example, this is how the actor error is stored.
```
ACTOR_DIED (metadata) | (empty)
```
The problem is this structure doesn't allow us to store meaning information regarding actor failure, since we only store the "type" of failure, but not the meaningful payload.

### Proposal
Improve the error message to include
1. The exact reason why actor is dead.
2. The next action item per different actor death.

### Implementation
1. Whenever actor is dead, GCS publishes the death information. We will include the information regarding "why actor is dead" here.
2. We will allow the error object to include "payload". The payload will be the protobuf message that includes metadata.
```
# Prev 
ACTOR_DIED (metadata) | (empty)

# New
ACTOR_DIED (metadata) | Serialized protobuf message (body)
```
3. Now we can store why actor dies with meaningful payload within the error object, meaning we can easily write good error message.

### Milestones
- [x] Include the "death cause" information whenever actor dies. #20528
- [x] Allow to create payload for error objects. #20714 
- [x] Propagate "death cause" to RayActorError. 
- [ ] Improve existing error messages

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment]
cc @scv119 @ericl This is the plan for improving actor died error message. I already have a semi-working prototype here https://github.com/ray-project/ray/pull/20535. I will stack PRs since it is a bit complex. 

Here's the example (not completed) output when I killed the actor using `ray.kill`.
```
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task. Cause: The actor is dead because it is killed by ray.kill.
```

**Comment by rkooo567** [comment]
It is a part of https://github.com/ray-project/ray/issues/20496

**Comment by rkooo567** [comment]
Existing error messages haven't been improved yet

**Comment by DmitriGekhtman** [comment]
hmm, would still be good to fix
