### ISSUE TITLE
[Feature] Introduce new APIs(default_actor_lifetime/kill_job) for job concept.

### ISSUE THREAD

**Issue by jovany-wang** [ray-project/ray#21128]
For addressing the issue https://github.com/ray-project/ray/issues/6715, after some discussions, we got the agreement on the conclusions.

We're proposing 3 APIs now.

API1: Initializing a job with setting all actors as detached. Something like
```python
ray.init(_default_actor_lifetime="detached")
```

API2: Introducing new state `DRIVET_EXITED` for job.
DRIVET_EXITED: indicating driver exited, but the job is still running. (Maybe some detached actors are running.)
FINISHED: indicating job is finished. Nothing is running of the job.

API3: Introducing `kill_job()` API to kill a job totally.

## Work Items
- [x] Introducing default actor lifetime API #21283
- [ ] Introducing `DRIVER_EXITED` state for job table.
- [ ] Introducing `kill_job(job)` API.
- [ ] Adding documents.
- [ ] Refining  #21279

**Comment by jovany-wang** [comment]
It seems `ray.init(default_actor_lifetime="detached")` is a P0.

**Comment by jovany-wang** [comment]
TODO: Add documents.

**Comment by jovany-wang** [comment]
We need move this forward. [rocket]

**Comment by jovany-wang** [comment]
@Catch-Bull CC

**Comment by jovany-wang** [comment]
We now have 2 options for job state transition.
#### 1. Introduce `DriverExited` state.
```bash
                                                    (2) MarkFailed
                    |-----------------------------------------------------------------------------> FAILED
                    |                                                                                 ^
 (1) ray.init()     |              (3) MarkFinished/KillJob                                           |
-----------------> RUNNING -----------------------------------------------> FINISHED                  |
                    |                                                          ^                      |
                    |                                                          |                      |
                    |  (4) MarkDriverExited                     (5) KillJob    |                      |
                    |------------------------> DRIVER_EXITED -------------------                      |
                                                      |                                               |
                                                      |         (6) detached actor gets dead          |
                                                      -------------------------------------------------                        
```


#### 2. Introduce a new field `driver_exited_code` for job table.
```bash

                             (2) MarkFailed / detached actor gets dead
                    |-----------------------------------------------------> FAILED
                    |                                                                                  
 (1) ray.init()     |              (3) MarkFinished / KillJob                                         
-----------------> RUNNING -----------------------------------------------> FINISHED                 
                  |      ^
                  |      |
                  |      |
                   ------
  (4) driver exits and still have detached actor
```
For option 2, when a driver, the state is still `RUNNING`(It also makes sense since there's detached actor).
@wuisawesome  @ericl @kfstorm @raulchen
