### ISSUE TITLE
[Feature] Make JVM aware of the memory of objects in memory store.

### ISSUE THREAD

**Issue by jovany-wang** [ray-project/ray#21218]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

#### Some backgrounds
- Full GC will be triggered in every 10min by default. https://github.com/ray-project/ray/blob/master/src/ray/common/ray_config_def.h#L294
- Object in in-memory store will be removed only if the ObjectRefImpl object is removed by JVM.  https://github.com/ray-project/ray/blob/master/java/runtime/src/main/java/io/ray/runtime/object/ObjectRefImpl.java#L125
- JVM only be aware of the ObjectRefImpl object instead of the real object in-memory store.

For example, Java `ObjectRefImpl` object is small(maybe 64B or smaller), and the real object in in-memory store maybe 10M, so in the view of JVM, it's 64B. The threshold has not been reached, so JVM doesn't trigger any GC.
If the QPS of these RayCalls is too large, the in-memory store is under pressure of memory but JVM is not able to be aware of it and doesn't trigger any GC.

#### Our proposal
We're proposing making JVM be aware of the in-memory store memory pressure by requesting allocating objects from JVM instead of allocating them in native.

We planed to make 3 PRs for it:
- [x] [Core] Refactor ray::RayObject to make it's able to be extended for allocating buffer from JVM. #21250
- [x] [Java] Manage the JVM buffers and ObjectRefs. #21441
- [x] [Java] Disable every 10min FullGC. #21443

**Comment by ericl** [comment]
Interesting, so this would be a Java-only allocator (since presumably these objects can't be used for zero-copy sharing with Python workers)?

I wonder if there's other ways to make the JVM aware of external memory pressure. cc @scv119

**Comment by jovany-wang** [comment]
> so this would be a Java-only allocator (since presumably these objects can't be used for zero-copy sharing with Python workers)?

Yes. It's only for Java right now. `JavaByteArrayBuffer::GetData()` will occur a copy from Java heap memory to native native.

**Comment by jovany-wang** [comment]
Not sure if Python worker has this kind of issue.

**Comment by scv119** [comment]
Ah.. Is there an alternative where we track the total size of in-memory allocated objects, and trigger GC when the size across some threshold (or using other more sophisticated policy)? Seems this way:
- Ray core has the control of the GC behavior(similar to how plasma store triggered GC)
- It also works with all language frontends out of box.
Thought?

**Comment by jovany-wang** [comment]
> Ray core has the control of the GC behavior(similar to how plasma store triggered GC)

I don't think Ray core GC is better than other language VMs. Some personal reasons are:
1. For an instance of JVM, the GC policy is complex and fine grained enough. JVM GC components do the decide on when and how to do the GCs. in-memory store doesn't like plasma, as plasma is a distributed memory awaring, and there is no such GC for distributed memory.
2. GC policies are not the same in different languages. Golang and JVM has a similar GC mechanism，but C++ and Rust are not with-GC languages.  It's hard to unify it.

But I didn't investigate it too deeply. Maybe we can find a sophisticated policy for it. That would be great.

I plan to do my this item first, at least for a short term plan. And I'm glad to discuss more possibilities for a long term plan.

**Comment by jovany-wang** [comment]
@scv119 Does python has the same issue?

**Comment by scv119** [comment]
> For an instance of JVM, the GC policy is complex and fine grained enough. JVM GC components make the decision on when and how to do the GCs. in-memory store doesn't like plasma, as plasma is a distributed memory awaring, and there is no such GC for distributed memory.

In the proposal, there are two piece of data known by JVM:

- the Ray object **metadata** (i.e., `ObjectRefImpl`), which is reference counted by JVM and the data size is small.
- the Ray object **data**, which is only reference counted once by JVM and the data size could potentially be large.

The language frontend doesn't have the connection that the metadata and the data belong to the same object. We rely on the assumption that the language frontend will GC the metadata when the data used up a lot of heap memory, even though the language frontend doesn't know the connection between these two.

The nice part of the proposal is we defer the GC decision to the language frontend (with the above assumption holds true); The down side, is we need a reverse of dependency that the Core depends on the language frontend for memory allocation, and maybe more scattered/inconsistent GC policies.

**Comment by scv119** [comment]
At a high level, we need to decide if the memory allocated in local object store is closer to language frontend or to core(plasma store). once decided this it will help us to decide where the code/logic lives.

**Comment by jovany-wang** [comment]
Hi @scv119 @ericl , before we get all agreements on the high level thoughts. Let us move this forward as our short term goal. This is the first PR #21250 you can take.
Note that this proposal doesn't break any of the current behaviors except Java Worker.

**Comment by jovany-wang** [comment]
All items were done.
