### ISSUE TITLE
[streaming] Track items on moving streaming to another repo. 

### ISSUE THREAD

**Issue by jovany-wang** [ray-project/ray#21602]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

- [x] Move main source code. @ashione #21770
- [x] Remove streaming deploying processing. #21603 @jovany-wang 
- [x] Remove CI from this repo. @ashione #21770
- [x] Remove streaming stuff from raydist.jar 

Anything else?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jovany-wang** [comment]
@ashione Could you remove them from building and CI?

**Comment by jovany-wang** [comment]
All were done.
