### ISSUE TITLE
[Datasets] [Docs] Refactor docs structure + Getting Started vs. User Guide content

### ISSUE THREAD

**Issue by clarkzinzow** [ray-project/ray#23088]
We are restructuring the Datasets docs into the following:
```
Ray Data
  - Getting Started with Ray Datasets
  - User Guides
    - Creating Datasets
    - Saving Datasets
    - Transforming Datasets
    - Exchanging Datasets
    - Pipelining Compute
    - ML Preprocessing
    - Working with Tensors
    - Performance Tips and Tuning
  - Key Concepts
  - Architecture
  - Example: Large-scale ML Ingest
  - Ray Datasets API
  - Integrations
    - Dask-on-Ray
    - Modin
    - Spark-on-Ray (RayDP)
    - Mars-on-Ray
```

## TODOs

- [x] Trim down Getting Started page to linear end-to-end example.
- [x] Remove DatasetPipelines from Getting Started page and de-emphasize/qualify throughout user guides (should only be used in advanced cases).
- [x] User Guide pages created/changed:
  - Creating Datasets - pulled from Getting Started
  - Saving Datasets - pulled from Getting Started
  - Transforming Datasets - pulled from Getting Started
  - Exchanging Datasets - pulled from Getting Started
  - Pipelining Compute - pulled from Getting Started
  - ML Preprocessing - rename "Data Loading and Preprocessing for ML Training"
- [x] Move third-party integrations to Integrations page
- [x] Update Ray Data landing page to contain the new User Guide page links (further updates to the landing page, e.g. overview of the data ecosystem, will happen in a future PR)

**Comment by maxpumperla** [comment]
@clarkzinzow thanks for further specifying this! Just a couple of comments:

- Let's make sure we align the [docs project](https://github.com/orgs/ray-project/projects/20/views/1?filterQuery=data) with your [UX initiative](https://github.com/ray-project/ray/issues/23091) so that we don't duplicate tickets.
- Can we merge key concepts and architecture in your above proposal? I think those usually naturally belong together. If the architecture goes too far, it might also be an "internals" user guide like for Tune.
- The single example with name looks a little sad. I know it takes time, but maybe we can have 2-3 examples at first and create a proper Examples section [as per this ticket](https://github.com/ray-project/ray/issues/21838).

**Comment by clarkzinzow** [comment]
Reopening since there are some remaining TODOs!

**Comment by clarkzinzow** [comment]
@maxpumperla Great feedback!

>Can we merge key concepts and architecture in your above proposal? I think those usually naturally belong together. If the architecture goes too far, it might also be an "internals" user guide like for Tune.

Agreed, the split-out of internal concepts (which is what the "architecture" page is supposed to document) is TBD/optional. I like the "internals" user guide, @naijoaix that seems like a good route to go if we have some architecture key concepts that are a bit too in-the-weeds!

**Comment by naijoaix** [comment]
I think architecture is not necessarily the thing as concepts and it has to show how things work together. Describing it at a high level hopefully is not a deep dive and would help users use datasets more effectively (such as building a mental model ready for self-serve debugging).

**Comment by clarkzinzow** [comment]
@naijoaix I get wanting to make that distinction between abstraction-type concepts and architecture, but I think that @maxpumperla would argue that those sort of high-level mental model building things (even if purely architecture) should be in the "Key Concepts" section, since that falls under the purview of "what concepts do I need to know to use Datasets" and we're aggressively trying to unify the common top-level docs pages for each library. E.g. the "Key Concepts" page could an "Architecture" section.

**Comment by naijoaix** [comment]
I think decoupling logically-separated things into their own units is exactly what refactoring should do.
Currently the Key Concepts contains 3 parts: Dataset, DatasetPipelines and Dataset Execution Model. I'd think Dataset Execution Model is not the same kind of things as Dataset/DatasetPipelines.
It's possible to structure these properly in one page. The concern is how long we want to expand this page (I think it will expand - speaking of concept, we need to tell users more basic things about a Dataset, like is it a bag or ordered list, like semantics of schema etc or other data model properties).

**Comment by zhe-thoughts** [comment]
@pcmoritz @clarkzinzow @jianoaix Let's move the Slack discussion around examples here. 

I think key decisions to make:

- What kind of examples should we have in Getting Started? "simple and crisp", or more representing real-world use cases?
- How much should we rely on external storage (S3) and how much "built-in" small files should we use?

I think having a number of small files (a few KBs) can be P0, and having some larger files on S3 could be P1. With a few KBs, we should be able to demonstrate the API and maybe some speedup with Ray. Thoughts?

cc @maxpumperla

**Comment by zhe-thoughts** [comment]
Is this issue still open (or resolved with recently merged PRs)?
