### ISSUE TITLE
[tune] Documentation + Usability Improvements

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#2402]
- [ ] Print traceback when FunctionRunner fails (wontfix for now, not often reproduced)
- [x] Document TrainingResult with class wrapper
- [x] Move TrainingResult to dict
- [x] Separate Scheduling from Execution (#2425, Fred/@alexbao)
- [x] Add citation note
- [ ] Add an FAQ + Annotated Documentation for Tune (#2728)
- [ ] Add logging functionality to Tune (#2847)

**Comment by richardliaw** [comment]
Closing as this has been split into separate issues.
