### ISSUE TITLE
[air] Documentation checklist for Beta

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#25533]
### Description

I'd like to make sure we check the following before releasing AIR for 2.0.0beta

- [x] No hardlinks when [cross-references can be used](https://docs.readthedocs.io/en/stable/guides/cross-referencing-with-sphinx.html#cross-referencing-with-sphinx)
- [x] All output types are documented
- [x] All docstrings actually read well
- [x] Notebooks can be downloaded
- [x] All code is tested
- [x] No personal strings in output
- [ ] Things are linked properly where users may want them to be linked properly.
- [ ] Make sure outputs, errors, and args are documented properly.

### Link

https://docs.ray.io/en/master/ray-air/getting-started.html
