### ISSUE TITLE
[AIR] Computer vision user workload on AIR tracking + success criteria

### ISSUE THREAD

**Issue by jiaodong** [ray-project/ray#28351]
Success criteria: Onboard one user's computer vision workload (Data IO + preprocessing + DDP Training) to AIR.

Open items 

- [ ] Create Ray dataset with representative data examples
- [ ] Data preprocessing
  - [ ] Placeholder for different stages
  - [ ] x 
- [ ] Feed into dummy TensorFlowTrainer
- [ ] TBD
