### ISSUE TITLE
[docs] AIR docs changes todo list

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#38365]
- [x] API pages need to be moved to the proper sections, out of ray-air @matthewdeng 
  - In particular, the https://docs.ray.io/en/master/ray-air/api/api.html page should be removed, and all underlying pages should be removed as well. Any APIs in these underlying pages should be migrated to their correct positions in corresponding libraries.
  - [x] started PR -https://github.com/ray-project/ray/pull/38427
  - [x] done in https://github.com/ray-project/ray/pull/38632
- [x] remove AIR references (first pass done, need to do a final pass) @richardliaw 
- [x] Move stuff out of Preprocessors doc page (@richardliaw)
  - [x] started pr (#38348)
- [x] remove examples @richardliaw 
  - [x] started pr - https://github.com/ray-project/ray/pull/38374
- [x] Refactor rest of examples (P1?)  @matthewdeng 
  - This mainly means that we should remove as many examples in ray-air/examples/ as possible, into `train/examples` and such
  - [x] #39298 
- [ ] Remove dead code and dead tests (NEED OWNER)
- [ ] Final pass @richardliaw

**Comment by anyscalesam** [comment]
The Train GA blocker is the top checklist. @matthewdeng to find owner.

**Comment by matthewdeng** [comment]
@richardliaw quick update on this:

1. I am not planning to remove dead code and tests for 2.7.
2. There is some minor cleanup in flight, e.g. for cleaning up some additional AIR/Train API references
3. I am planning to do another pass over for references to AIR (in particular in the Train docs)

Could you start doing a broader pass over all the documentation, to see if there is anything else?
