### ISSUE TITLE
[core][compiled graphs] Meta-issue: Visualization for Compiled Graphs

### ISSUE THREAD

**Issue by ruisearch42** [ray-project/ray#48192]
### Description

This is a meta-issue to track progress for compiled graph visualization tasks:

Roadmap

- [ ] https://github.com/ray-project/ray/issues/47945
- [ ] https://github.com/ray-project/ray/issues/48191
- [ ] https://github.com/ray-project/ray/issues/48190
