### ISSUE TITLE
[Release] Release 0.7.2

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#5067]
This issue will be used to track 0.7.2 release. 

- [x] bump version to `0.7.2` (#5066)
   - In `python/ray/__init.py`: (#5066)
   - In `src/ray/raylet/main.cc`: (#5070)
- [x] bump version to `0.8.0.dev2` (#5069)
- [x] Create a release branch (https://github.com/ray-project/ray/tree/releases/0.7.2)
- [x] Run stress test.
    - Stress tests passed
    - Application stress tests
        - Impala tests passed (in python2.7, we have to apply a workaround #5095)
        - SGD tests skipped (on path to deprecation #5093)
- [x] Resolve release blockers
    - Not aware of any release blockers
- [x] Download wheels, check they can be installed

|   |Linux   |Mac   |   
|---|---|---|
|2.7   |  ✅|   ✅|
| 3.5  |  ✅ |  ✅ | 
|  3.6 |  ✅ |  ✅|   
|3.7 | ✅ |✅  |

- [x] Final testing on Ubuntu and MacOS
- [x] Upload to PyPI Test
    - [x] So it's installable via `pip install --index-url https://test.pypi.org/simple/ ray`
- [x] Upload to PyPI
- [x] Create a GitHub Release
    - [x] Draft release note
- [x] Update version numbers throughout codebase (Closed by #5186)
- [x] Improve release process (Closed by #5187)

**Comment by simon-mo** [comment]
Release wheels:


| Linux                                                                                                                                                          | Mac                                                                                                                                                           |
|:---------------------------------------------------------------------------------------------------------------------------------------------------------------|:--------------------------------------------------------------------------------------------------------------------------------------------------------------|
| [Python 2.7](https://s3-us-west-2.amazonaws.com/ray-wheels/releases/0.7.2/6e6cbb6b63a8f2479d1522a416e1dc4a5a2ad59f/ray-0.7.2-cp27-cp27mu-manylinux1_x86_64.wh) | [Python 2.7](https://s3-us-west-2.amazonaws.com/ray-wheels/releases/0.7.2/6e6cbb6b63a8f2479d1522a416e1dc4a5a2ad59f/ray-0.7.2-cp27-cp27m-macosx_10_6_intel.wh) |
| [Python 3.5](https://s3-us-west-2.amazonaws.com/ray-wheels/releases/0.7.2/6e6cbb6b63a8f2479d1522a416e1dc4a5a2ad59f/ray-0.7.2-cp35-cp35m-manylinux1_x86_64.wh)  | [Python 3.5](https://s3-us-west-2.amazonaws.com/ray-wheels/releases/0.7.2/6e6cbb6b63a8f2479d1522a416e1dc4a5a2ad59f/ray-0.7.2-cp35-cp35m-macosx_10_6_intel.wh) |
| [Python 3.6](https://s3-us-west-2.amazonaws.com/ray-wheels/releases/0.7.2/6e6cbb6b63a8f2479d1522a416e1dc4a5a2ad59f/ray-0.7.2-cp36-cp36m-manylinux1_x86_64.wh)  | [Python 3.6](https://s3-us-west-2.amazonaws.com/ray-wheels/releases/0.7.2/6e6cbb6b63a8f2479d1522a416e1dc4a5a2ad59f/ray-0.7.2-cp36-cp36m-macosx_10_6_intel.wh) |
| [Python 3.7](https://s3-us-west-2.amazonaws.com/ray-wheels/releases/0.7.2/6e6cbb6b63a8f2479d1522a416e1dc4a5a2ad59f/ray-0.7.2-cp37-cp37m-manylinux1_x86_64.wh)  | [Python 3.7](https://s3-us-west-2.amazonaws.com/ray-wheels/releases/0.7.2/6e6cbb6b63a8f2479d1522a416e1dc4a5a2ad59f/ray-0.7.2-cp37-cp37m-macosx_10_6_intel.wh) |

**Comment by simon-mo** [comment]
Draft Release Note:
```
Core
----
- [C++] Add hash table to Redis-Module (#4911) (Author Yuhong Guo)
- [Core worker] Add metadata support in object interface (#5031) (Author Kai Yang)
- [Core worker] add store & task provider (#4966) (Author Zhijun Fu)
- [core worker] add task submission & execution interface (#4922) (Author Zhijun Fu)
- [Core Worker] implement ObjectInterface and add test framework (#4899) (Author Zhijun Fu)
- [Core worker] Task execution passes TaskInfo struct to executor (#5032) (Author Kai Yang)
- [core] Add dynamic worker options for worker command. (#4970) (Author Qing Wang)
- [core] Better organize ray_common module (#4898) (Author Hao Chen)
- [core] fetching objects in parallel in _get_arguments_for_execution (#4775) (Author Akshat Gokhale)
- [core] Fix a crash when unknown worker registering to raylet (#4992) (Author Qing Wang)
- [core] Fix driver id in TaskInfo (#5055) (Author Hao Chen)
- [core] Fix memory leak in rpc ServerCall and ClientCall (#5046) (Author Hao Chen)
- [core] Fix no cpus test (#5009) (Author Joey Jiang)
- [core] Fix resource bookkeeping bug with acquiring unknown resource. (#4945) (Author Robert Nishihara)
- [core] Fix test_task_forward (#5040) (Author Hao Chen)
- [core] Flush lineage cache on task submission instead of execution (#4942) (Author Stephanie Wang)
- [core] Hotfix for change of from_random to FromRandom (#4909) (Author Yuhong Guo)
- [core] Inherit Function Docstrings and other metedata (#4985) (Author Simon Mo)
- [core] Initial high-level code structure of CoreWorker. (#4875) (Author Hao Chen)
- [core] Refactor ID Serial 2: change all ID functions to `CamelCase` (#4896) (Author Yuhong Guo)
- [core] Refactor redis callback handling (#4841) (Author Qing Wang)
- [core] Remove debug check for uncommitted lineage (#5038) (Author Stephanie Wang)
- [core] Remove typing from setup.py install_requirements. (#4971) (Author Robert Nishihara)
- [core] Use gRPC to handle communication and data transmission between object manager (#4996) (Author Joey Jiang)
- [core] Use int64_t instead of int to keep track of fractional resources (#4959) (Author Philipp Moritz)
- [core] Use proper session directory for debug_string.txt (#4960) (Author Philipp Moritz)
- [core] Flush all tasks from local lineage cache after a node failure (#4964) (Author Stephanie Wang)
- [gRPC] Migrate gcs data structures to protobuf (#5024) (Author Hao Chen)
- [grpc] refactor rpc server to support multiple io services (#5023) (Author Zhijun Fu)
- [gRPC] Use gRPC for inter-node-manager communication (#4968) (Author Hao Chen)
- [ID Refactor] Rename DriverID to JobID (#5004) (Author Qing Wang)
- [Java] Add inner class `Builder` to build call options. (#4956) (Author Qing Wang)
- [Java] Fix bug of `BaseID` in multi-threading case. (#4974) (Author Qing Wang)
- [Java] Fix serializing issues of `RaySerializer` (#4887) (Author Qing Wang)

Tune
----
- [tune] Add requirements-dev.txt and update docs for contributing (#4925) (Author Timon Ruban)
- [tune] Directional metrics for components (#4120) (#4915) (Author Hersh Godse)
- [tune] Disallow setting resources_per_trial when it is already configured (#4880) (Author Eric Liang)
- [tune] Make PBT Quantile fraction configurable (#4912) (Author Timon Ruban)
- [tune] Pretty print params json in logger.py (#4903) (Author Kristian Hartikainen)
- [tune] Tutorial UX Changes (#4990) (Author Richard Liaw)
- [tune] Update MNIST Example (#4991) (Author Richard Liaw)

RLlib
-----
- [rllib] Add QMIX mixer parameters to optimizer param list (#5014) (Author Eric Liang)
- [rllib] Add docs on how to use TF eager execution (#4927) (Author Eric Liang)
- [rllib] Allow Torch policies access to full action input dict in extra_action_out_fn (#4894) (Author Eric Liang)
- [rllib] Allow access to batches prior to postprocessing (#4871) (Author Eric Liang)
- [rllib] Fix DDPG example (#4973) (Author Eric Liang)
- [rllib] Fix Multidiscrete support (#4869) (Author Eric Liang)
- [rllib] Fix documentation on custom policies (#4910) (Author Eric Liang)
- [rllib] Give error if sample_async is used with pytorch for A3C (#5000) (Author Philipp Moritz)
- [rllib] Port remainder of algorithms to build_trainer() pattern (#4920) (Author Eric Liang)
- [rllib] Rename PolicyEvaluator => RolloutWorker (#4820) (Author Eric Liang)
- [rllib] Rough port of DQN to build_tf_policy() pattern (#4823) (Author Eric Liang)
- [rllib] Add preprocessing example to offline documentation (#4950) (Author Eric Liang)
- [rllib] Fix bugs in the a3c code template. (#4984) (Author Tianhong Dai)

Other Libraries
---------------
- [sgd] Add non-distributed PyTorch runner (#4933) (Author Peter Schafhalter)
- [sgd] Distributed Training via PyTorch (#4797) (Author Peter Schafhalter)
- [autoscaler] autoscaler/monitor: Kill workers on exception (#4997) (Author Daniel Edgecumbe)
- [autoscaler] Fix local cluster yaml (#4918) (Author Richard Liaw)
- [signal] fix handling of non-integral timeout values in signal.receive (#5002) (Author Andrew Berger)


CI/Infra/Doc
--------
- [ci] Change Jenkins to py3 (#5022) (Author Richard Liaw)
- [ci] Drop duplicated string format (#4897) (Author Si-Yuan)
- [ci] Fix Java CI failure (#4995) (Author Qing Wang)
- [ci] Fix master's linting (#5049) (Author Qing Wang)
- [ci] Fix tensorflow-1.14 installation in jenkins (#5007) (Author Philipp Moritz)
- [ci] Fix valgrind build by installing new version of valgrind (#5008) (Author Philipp Moritz)
- [ci] Lengthen buffer in resource test. (#4961) (Author Robert Nishihara)
- [ci] Make release stress tests work and improve them. (#4955) (Author Robert Nishihara)
- [ci] Make some fixes to long running stress tests. (#5056) (Author Robert Nishihara)
- [ci] temp fix for build (#5006) (Author Eric Liang)
- [ci] Update aws keys for uploading wheels to s3. (#4948) (Author Robert Nishihara)
- [ci] Update to latest arrow (#5011) (Author Philipp Moritz)
- [ci] Update VersionKey in stats (#5070) (Author Simon Mo)
- [ci] Upgrade CI clang-format to 6.0 (#4976) (Author Hao Chen)
- [ci] Upload wheels on Travis to branchname/commit_id. (#4949) (Author Robert Nishihara)
- [ci] Use bazel disk cache with travis (#5068) (Author Simon Mo)
- [doc] Update developer docs with bazel instructions (#4944) (Author Stephanie Wang)
- [doc] Update version number in documentation after release 0.7.0 -> 0.7.1 and 0.8.0.dev0 -> 0.8.0.dev1. (#4941) (Author Robert Nishihara)
- [docs] docs for running Tensorboard without sudo (#5015) (Author Ashwinee Panda)
```

**Comment by simon-mo** [comment]
Closed by #5187, #5186
