### ISSUE TITLE
ID Refactor

### ISSUE THREAD

**Issue by jovany-wang** [ray-project/ray#5285]
As discussed before, we'd like to embed info to IDs. This issue is used to trace the processes of refactoring IDs.

Related doc: https://docs.google.com/document/d/1eXbwzRNgnmjiVeRlOzdKHUUquTxro8fI1PTMdKwMeGc/edit

TODOs:
- [x] Rename `JobID` (PR:#5004)
- [x] Short `JobID` to 4 bytes and generated from GCS (PR:#5110)
- [x] Embed `JobID` -> `ActorID`->`TaskID` ->`ObjectID`  (PR:#5286)
- [ ] Use bit-fileds to store `ID`s data instead of `unint8_t []` (suggested by @pcmoritz)
- [ ] Remove unnecessary info because info were embedded into IDs
- [ ] Separate `NodeID` from `ClientID`
- [ ] Separate `WorkerID` from `ClientID` in some cases
- [ ] Remove implementation of Java IDs, just wrap by JNI
- [ ] Make Each class occupies a separate file and make `length` as template param

etc
